[package]
name = "deps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = { path = "../..", features = ["in-use-encryption-unstable"] }
futures = "0.3"
once_cell = "1.10.0"
rand = "0.8.5"

[dev-dependencies]
tokio = "1.23.0"
anyhow = { version = "1.0.66", features = ["backtrace"] }